// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44365' | (string & {});
};

export type RollbackPreviewerConfigurationResponse = {
    enableFrontendPreviewAuthorisation: boolean;
    frontendPreviewAuthorisationSecret?: string | null;
    isTimeLimited: boolean;
    expirationMinutes?: number | null;
};

export type GetUmbracoRollbackpreviewerApiV1ConfigurationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/rollbackpreviewer/api/v1/configuration';
};

export type GetUmbracoRollbackpreviewerApiV1ConfigurationErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetUmbracoRollbackpreviewerApiV1ConfigurationResponses = {
    /**
     * OK
     */
    200: RollbackPreviewerConfigurationResponse;
};

export type GetUmbracoRollbackpreviewerApiV1ConfigurationResponse = GetUmbracoRollbackpreviewerApiV1ConfigurationResponses[keyof GetUmbracoRollbackpreviewerApiV1ConfigurationResponses];
